Задание 1

In [1]:
import numpy as np

In [2]:
#1
N=10
np.array([ np.array([ (i+j)%2 for j in range(N)]) for i in range(N)])

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [3]:
#2
a = np.array([1.0, 2.0, 5.0])
b = np.array([1., 2., 4.])
scalar = np.dot(a,b)
vector = np.cross(a,b)
print("угол через косинус:",np.arccos(scalar / (np.linalg.norm(a) * np.linalg.norm(b)) ) )
print("угол через синус:",np.arcsin(np.linalg.norm(vector) / (np.linalg.norm(a) * np.linalg.norm(b)) ))

угол через косинус: 0.08920534354754166
угол через синус: 0.0892053435475418


In [4]:
#3
a = np.random.randint(1, 100, size = (4, 4,2,2))
b = np.random.randint(1, 100, size = (4, 4,4,2))
np.intersect1d(a.flatten(), b.flatten())

array([ 4,  6,  7,  8,  9, 11, 12, 13, 18, 21, 26, 32, 33, 35, 37, 41, 47,
       49, 52, 54, 60, 64, 65, 68, 72, 73, 75, 78, 79, 89, 90, 95, 96])

In [5]:
#4
N = 5
A = np.random.random( size = (N, N))
b = np.random.random( size = (N,1))
np.linalg.solve(A,b)

array([[-1.26938084],
       [ 0.01731607],
       [ 0.65143979],
       [ 0.04813075],
       [ 0.80833635]])

Задание 2

In [15]:
sizeImage = 28 
N = 10
data =  np.array([ np.random.random( size = (1, sizeImage,sizeImage)) for i in range(N) ]) 
class generator:
   def __init__(self, data, sizeBatch,takeLastElement):
        self.data = data
        self.sizeBatch = sizeBatch
        self.takeLastElement = takeLastElement
        self.position = 0 
   def __iter__(self):
        return self
   def get_next_batch(self):
     fragment = self.data[self.position:self.position+self.sizeBatch]
     self.position = self.position + self.sizeBatch
     return fragment
   def __next__(self):
        fragment = self.get_next_batch()
        if fragment.shape[0] < self.sizeBatch :
           if self.takeLastElement and fragment.shape[0]>0 :
             return fragment
           raise StopIteration
        return fragment
dataset1 = generator(data,3,True)
dataset2 = generator(data,4,False)

In [16]:
for features in dataset1:
  print(features.shape)
 

(3, 1, 28, 28)
(3, 1, 28, 28)
(3, 1, 28, 28)
(1, 1, 28, 28)


In [17]:
for features in dataset2:
  print(features.shape)

(4, 1, 28, 28)
(4, 1, 28, 28)
